server:
  port: 8080

spring:
  datasource:
    username: root
    password: zhuwomenhaoyun
    url: jdbc:mysql:///permission

mybatis-plus:
  type-aliases-package: com.company.permission.common.model
  mapper-locations: classpath*:mapper/**/*.xml


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
